package com.kcbgroup.main.utils;

public class Utils {
	
	 public int generate() {
		    int min = 100000901;
		    int max = 999999999;
	        return min + (int)(Math.random() * ((max - min) + 1));
	 }
	
	public String mockCreateAccountResponse() {
	
		String createAccountResponse = "<S:Envelope xmlns:S=\"http://schemas.xmlsoap.org/soap/envelope/\">\r\n"
				+ "   <S:Body>\r\n"
				+ "      <ns6:KCBAccountCreationResponse xmlns:ns6=\"http://temenos.com/T24KCBAccountOpening\" xmlns:ns5=\"http://temenos.com/ACCOUNTKCBCHANNELS\" xmlns:ns4=\"http://temenos.com/CUSTOMER\" xmlns:ns3=\"http://temenos.com/CUSTOMERKCBCHANNELS\" xmlns:ns2=\"http://temenos.com/ACCOUNT\">\r\n"
				+ "         <Status>\r\n"
				+ "            <transactionId>1282941852</transactionId>\r\n"
				+ "            <messageId/>\r\n"
				+ "            <successIndicator>Success</successIndicator>\r\n"
				+ "            <application>ACCOUNT</application>\r\n"
				+ "         </Status>\r\n"
				+ "         <ACCOUNTType id=\"1282941852\">\r\n"
				+ "            <ns2:CUSTOMER>47797164</ns2:CUSTOMER>\r\n"
				+ "            <ns2:CATEGORY>6004</ns2:CATEGORY>\r\n"
				+ "            <ns2:ACCOUNTTITLE1>MWE TESTING</ns2:ACCOUNTTITLE1>\r\n"
				+ "            <ns2:ACCOUNTTITLE2>MWE TESTING</ns2:ACCOUNTTITLE2>\r\n"
				+ "            <ns2:SHORTTITLE>MWE TESTING</ns2:SHORTTITLE>\r\n"
				+ "            <ns2:POSITIONTYPE>TR</ns2:POSITIONTYPE>\r\n"
				+ "            <ns2:CURRENCY>KES</ns2:CURRENCY>\r\n"
				+ "            <ns2:CURRENCYMARKET>1</ns2:CURRENCYMARKET>\r\n"
				+ "            <ns2:ACCOUNTOFFICER>4001</ns2:ACCOUNTOFFICER>\r\n"
				+ "            <ns2:CONDITIONGROUP>11228</ns2:CONDITIONGROUP>\r\n"
				+ "            <ns2:gCAPDATECHARGE>\r\n"
				+ "               <ns2:CAPDATECHARGE>20210228</ns2:CAPDATECHARGE>\r\n"
				+ "            </ns2:gCAPDATECHARGE>\r\n"
				+ "            <ns2:PASSBOOK>NO</ns2:PASSBOOK>\r\n"
				+ "            <ns2:OPENINGDATE>20210203</ns2:OPENINGDATE>\r\n"
				+ "            <ns2:OPENCATEGORY>6004</ns2:OPENCATEGORY>\r\n"
				+ "            <ns2:CHARGECCY>KES</ns2:CHARGECCY>\r\n"
				+ "            <ns2:CHARGEMKT>1</ns2:CHARGEMKT>\r\n"
				+ "            <ns2:INTERESTCCY>KES</ns2:INTERESTCCY>\r\n"
				+ "            <ns2:INTERESTMKT>1</ns2:INTERESTMKT>\r\n"
				+ "            <ns2:gALTACCTTYPE>\r\n"
				+ "               <ns2:mALTACCTTYPE>\r\n"
				+ "                  <ns2:ALTACCTTYPE>LEGACY</ns2:ALTACCTTYPE>\r\n"
				+ "               </ns2:mALTACCTTYPE>\r\n"
				+ "               <ns2:mALTACCTTYPE>\r\n"
				+ "                  <ns2:ALTACCTTYPE>T24.IBAN</ns2:ALTACCTTYPE>\r\n"
				+ "               </ns2:mALTACCTTYPE>\r\n"
				+ "               <ns2:mALTACCTTYPE>\r\n"
				+ "                  <ns2:ALTACCTTYPE>PREV.IBAN</ns2:ALTACCTTYPE>\r\n"
				+ "               </ns2:mALTACCTTYPE>\r\n"
				+ "            </ns2:gALTACCTTYPE>\r\n"
				+ "            <ns2:ALLOWNETTING>NO</ns2:ALLOWNETTING>\r\n"
				+ "            <ns2:HVTFLAG>NO</ns2:HVTFLAG>\r\n"
				+ "            <ns2:gOVERRIDE>\r\n"
				+ "               <ns2:OVERRIDE>KCB.DAO.MISMATCH}Branch Code Mismatch: Transaction Not for User's Branch</ns2:OVERRIDE>\r\n"
				+ "               <ns2:OVERRIDE>KCB.DAO.MISMATCH}Branch Code Mismatch: Transaction Not for User's Branch</ns2:OVERRIDE>\r\n"
				+ "            </ns2:gOVERRIDE>\r\n"
				+ "            <ns2:CURRNO>1</ns2:CURRNO>\r\n"
				+ "            <ns2:gINPUTTER>\r\n"
				+ "               <ns2:INPUTTER>2760_COB__OFS_TWS</ns2:INPUTTER>\r\n"
				+ "            </ns2:gINPUTTER>\r\n"
				+ "            <ns2:gDATETIME>\r\n"
				+ "               <ns2:DATETIME>2102031205</ns2:DATETIME>\r\n"
				+ "            </ns2:gDATETIME>\r\n"
				+ "            <ns2:AUTHORISER>2760_COB_OFS_TWS</ns2:AUTHORISER>\r\n"
				+ "            <ns2:COCODE>KE0010001</ns2:COCODE>\r\n"
				+ "            <ns2:DEPTCODE>4905</ns2:DEPTCODE>\r\n"
				+ "            <ns2:KCBACSUBSEGMEN>7131</ns2:KCBACSUBSEGMEN>\r\n"
				+ "            <ns2:ACTR8CATEG>9999</ns2:ACTR8CATEG>\r\n"
				+ "            <ns2:EMPLOYEENO>A9099100101</ns2:EMPLOYEENO>\r\n"
				+ "            <ns2:DSACODE>KECEDSR10397</ns2:DSACODE>\r\n"
				+ "            <ns2:gDSA.SUP>\r\n"
				+ "               <ns2:DSASUP>KECEDSR10397</ns2:DSASUP>\r\n"
				+ "            </ns2:gDSA.SUP>\r\n"
				+ "            <ns2:OFFUNIQREF>OFF1234EEE30</ns2:OFFUNIQREF>\r\n"
				+ "         </ACCOUNTType>\r\n"
				+ "      </ns6:KCBAccountCreationResponse>\r\n"
				+ "   </S:Body>\r\n"
				+ "</S:Envelope>";
		
		return createAccountResponse;
		
	}
	
	public String mockCreateCustomerResponse() {
		
		String createCustomerResponse = "<S:Envelope xmlns:S=\"http://schemas.xmlsoap.org/soap/envelope/\">\r\n"
				+ "   <S:Body>\r\n"
				+ "      <ns6:KCBCustomerCreationResponse xmlns:ns6=\"http://temenos.com/T24KCBAccountOpening\" xmlns:ns5=\"http://temenos.com/ACCOUNTKCBCHANNELS\" xmlns:ns4=\"http://temenos.com/CUSTOMER\" xmlns:ns3=\"http://temenos.com/CUSTOMERKCBCHANNELS\" xmlns:ns2=\"http://temenos.com/ACCOUNT\">\r\n"
				+ "         <Status>\r\n"
				+ "            <transactionId>47797164</transactionId>\r\n"
				+ "            <messageId/>\r\n"
				+ "            <successIndicator>Success</successIndicator>\r\n"
				+ "            <application>CUSTOMER</application>\r\n"
				+ "         </Status>\r\n"
				+ "         <CUSTOMERType id=\"47797164\">\r\n"
				+ "            <ns4:MNEMONIC>ID336112T</ns4:MNEMONIC>\r\n"
				+ "            <ns4:gSHORTNAME>\r\n"
				+ "               <ns4:SHORTNAME>MWE TEST</ns4:SHORTNAME>\r\n"
				+ "            </ns4:gSHORTNAME>\r\n"
				+ "            <ns4:gNAME1>\r\n"
				+ "               <ns4:NAME1>MWE TESTING</ns4:NAME1>\r\n"
				+ "            </ns4:gNAME1>\r\n"
				+ "            <ns4:gSTREET>\r\n"
				+ "               <ns4:STREET>KENCOM HOUSE TRAINING</ns4:STREET>\r\n"
				+ "            </ns4:gSTREET>\r\n"
				+ "            <ns4:gTOWNCOUNTRY>\r\n"
				+ "               <ns4:TOWNCOUNTRY>NAIROBI</ns4:TOWNCOUNTRY>\r\n"
				+ "            </ns4:gTOWNCOUNTRY>\r\n"
				+ "            <ns4:SECTOR>1001</ns4:SECTOR>\r\n"
				+ "            <ns4:ACCOUNTOFFICER>4001</ns4:ACCOUNTOFFICER>\r\n"
				+ "            <ns4:INDUSTRY>1699</ns4:INDUSTRY>\r\n"
				+ "            <ns4:TARGET>11</ns4:TARGET>\r\n"
				+ "            <ns4:NATIONALITY>KE</ns4:NATIONALITY>\r\n"
				+ "            <ns4:CUSTOMERSTATUS>1</ns4:CUSTOMERSTATUS>\r\n"
				+ "            <ns4:RESIDENCE>KE</ns4:RESIDENCE>\r\n"
				+ "            <ns4:gLEGALID>\r\n"
				+ "               <ns4:mLEGALID>\r\n"
				+ "                  <ns4:LEGALID>3361121T</ns4:LEGALID>\r\n"
				+ "                  <ns4:LEGALDOCNAME>ID.KE</ns4:LEGALDOCNAME>\r\n"
				+ "                  <ns4:LEGALHOLDERNAME>MWE TESTING</ns4:LEGALHOLDERNAME>\r\n"
				+ "                  <ns4:LEGALISSAUTH>GOK</ns4:LEGALISSAUTH>\r\n"
				+ "                  <ns4:LEGALISSDATE>20170202</ns4:LEGALISSDATE>\r\n"
				+ "               </ns4:mLEGALID>\r\n"
				+ "            </ns4:gLEGALID>\r\n"
				+ "            <ns4:LANGUAGE>1</ns4:LANGUAGE>\r\n"
				+ "            <ns4:COMPANYBOOK>KE0010001</ns4:COMPANYBOOK>\r\n"
				+ "            <ns4:CLSCPARTY>NO</ns4:CLSCPARTY>\r\n"
				+ "            <ns4:gCRPROFILETYPE>\r\n"
				+ "               <ns4:mCRPROFILETYPE>\r\n"
				+ "                  <ns4:CRPROFILETYPE>LOYALTY</ns4:CRPROFILETYPE>\r\n"
				+ "                  <ns4:CRPROFILE>BLUE</ns4:CRPROFILE>\r\n"
				+ "               </ns4:mCRPROFILETYPE>\r\n"
				+ "            </ns4:gCRPROFILETYPE>\r\n"
				+ "            <ns4:gPHONE1>\r\n"
				+ "               <ns4:mPHONE1>\r\n"
				+ "                  <ns4:PHONE1>9090909011</ns4:PHONE1>\r\n"
				+ "                  <ns4:EMAIL1>qwertyu123@gmail.com</ns4:EMAIL1>\r\n"
				+ "               </ns4:mPHONE1>\r\n"
				+ "            </ns4:gPHONE1>\r\n"
				+ "            <ns4:gLEGALIDDOCNAME>\r\n"
				+ "               <ns4:LEGALIDDOCNAME>3361121T-ID.KE</ns4:LEGALIDDOCNAME>\r\n"
				+ "            </ns4:gLEGALIDDOCNAME>\r\n"
				+ "            <ns4:AMLCHECK>NULL</ns4:AMLCHECK>\r\n"
				+ "            <ns4:AMLRESULT>NULL</ns4:AMLRESULT>\r\n"
				+ "            <ns4:INTERNETBANKINGSERVICE>NULL</ns4:INTERNETBANKINGSERVICE>\r\n"
				+ "            <ns4:MOBILEBANKINGSERVICE>NULL</ns4:MOBILEBANKINGSERVICE>\r\n"
				+ "            <ns4:gOVERRIDE>\r\n"
				+ "               <ns4:OVERRIDE>NATID/CUS*100 FROM 47797164 NOT RECEIVED</ns4:OVERRIDE>\r\n"
				+ "            </ns4:gOVERRIDE>\r\n"
				+ "            <ns4:CURRNO>1</ns4:CURRNO>\r\n"
				+ "            <ns4:gINPUTTER>\r\n"
				+ "               <ns4:INPUTTER>96134_COB__OFS_TWS</ns4:INPUTTER>\r\n"
				+ "            </ns4:gINPUTTER>\r\n"
				+ "            <ns4:gDATETIME>\r\n"
				+ "               <ns4:DATETIME>2102031125</ns4:DATETIME>\r\n"
				+ "            </ns4:gDATETIME>\r\n"
				+ "            <ns4:AUTHORISER>96134_COB_OFS_TWS</ns4:AUTHORISER>\r\n"
				+ "            <ns4:COCODE>KE9990001</ns4:COCODE>\r\n"
				+ "            <ns4:DEPTCODE>4905</ns4:DEPTCODE>\r\n"
				+ "            <ns4:KCBSECTOR>1001</ns4:KCBSECTOR>\r\n"
				+ "            <ns4:KCBCUSSEGMENT>8100</ns4:KCBCUSSEGMENT>\r\n"
				+ "            <ns4:gKCB.DOC.NAME>\r\n"
				+ "               <ns4:mKCB.DOC.NAME>\r\n"
				+ "                  <ns4:KCBDOCNAME>NATIONAL.ID</ns4:KCBDOCNAME>\r\n"
				+ "                  <ns4:KCBDOCID>3361121T</ns4:KCBDOCID>\r\n"
				+ "                  <ns4:KCBISSAUTH>GOK</ns4:KCBISSAUTH>\r\n"
				+ "                  <ns4:KCBISSDATE>20170202</ns4:KCBISSDATE>\r\n"
				+ "               </ns4:mKCB.DOC.NAME>\r\n"
				+ "            </ns4:gKCB.DOC.NAME>\r\n"
				+ "         </CUSTOMERType>\r\n"
				+ "      </ns6:KCBCustomerCreationResponse>\r\n"
				+ "   </S:Body>\r\n"
				+ "</S:Envelope>";
		
		return createCustomerResponse;
	}

}
